URL_SERVICE = "https://fad56420-e3b9-4fd5-9ff1-a9dbc38ce30a.serverhub.praktikum-services.ru"
DOC_PATH = "https://fad56420-e3b9-4fd5-9ff1-a9dbc38ce30a.serverhub.praktikum-services.ru"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"